[repositories.NI-Switch-Relay-Custom-Device]
release_branches = [ "master",]
build_number = 2

[repositories.CAN-Frame-Protection-Custom-Device]
build_number = 6

[repositories.Chassis-TimeSync-Custom-Device]
build_number = 6
release_branches = [ "master", "develop",]

