[repositories.BCI-SLSC-LOAD]
build_number = 7

[repositories.BCI-SLSC-VDT]
build_number = 9

[repositories.BCI-LOAD-TEMP]
build_number = 2

[repositories.group-switching-custom-device]
build_number = 5

[repositories.Switch-Custom-Device]
build_number = 12
