[repositories.BCI-SLSC-LOAD]
build_number = 16

[repositories.BCI-SLSC-VDT]
build_number = 13

[repositories.group-switching-custom-device]
build_number = 16

[repositories.commonbuild-configuration]

[repositories.Switch-Custom-Device]
build_number = 19
