[repositories.NI-Switch-Relay-Custom-Device]
2017_build_number = 1

[repositories.CAN-Frame-Protection-Custom-Device]
2017_build_number = 6

[repositories.Chassis-TimeSync-Custom-Device]
2015_build_number = 6
2017_release_branches = [ "master", "develop",]
2016_build_number = 8
2017_build_number = 60
