[repositories.BCI-SLSC-LOAD]
build_number = 9

[repositories.BCI-SLSC-VDT]
build_number = 7

[repositories.group-switching-custom-device]
build_number = 9

[repositories.commonbuild-configuration]

[repositories.Switch-Custom-Device]
build_number = 14
