[repositories.BCI-SLSC-LOAD]
build_number = 8

[repositories.BCI-SLSC-VDT]
build_number = 6

[repositories.group-switching-custom-device]
build_number = 9

[repositories.commonbuild-configuration]

[repositories.Switch-Custom-Device]
build_number = 14
