[repositories.BCI-SLSC-LOAD]
build_number = 14

[repositories.BCI-SLSC-VDT]
build_number = 11

[repositories.group-switching-custom-device]
build_number = 11

[repositories.commonbuild-configuration]

[repositories.Switch-Custom-Device]
build_number = 17
