[repositories.BCI-SLSC-LOAD]
release_branches = [ "master",]
build_number = 8

[repositories.BCI-SLSC-VDT]
release_branches = [ "master",]
build_number = 5

[repositories.group-switching-custom-device]
release_branches = [ "master",]
build_number = 5

[repositories.commonbuild-configuration]

[repositories.Switch-Custom-Device]
release_branches = [ "master",]
build_number = 13
