[repositories.CAN-Frame-Protection-Custom-Device]
2017_build_number = 6

[repositories.Chassis-TimeSync-Custom-Device]
2015_build_number = 5
2017_release_branches = [ "master", "develop",]
2016_build_number = 7
2017_build_number = 57
