[repositories.BCI-SLSC-LOAD]
build_number = 17

[repositories.BCI-SLSC-VDT]
build_number = 14

[repositories.BCI-LOAD-TEMP]
build_number = 2

[repositories.group-switching-custom-device]
build_number = 16

[repositories.commonbuild-configuration]

[repositories.Switch-Custom-Device]
build_number = 21
