[repositories.BCI-SLSC-LOAD]
build_number = 0

[repositories.group-switching-custom-device]
build_number = 0

[repositories.commonbuild-configuration]

[repositories.Switch-Custom-Device]
release_branches = [ "master",]
build_number = 6
