[repositories.BCI-SLSC-LOAD]
release_branches = [ "master",]
build_number = 3

[repositories.BCI-SLSC-VDT]
release_branches = [ "master",]
build_number = 2

[repositories.group-switching-custom-device]
release_branches = [ "master",]
build_number = 0

[repositories.commonbuild-configuration]

[repositories.Switch-Custom-Device]
release_branches = [ "master",]
build_number = 6
