[repositories.BCI-SLSC-LOAD]
build_number = 15

[repositories.BCI-SLSC-VDT]
build_number = 12

[repositories.group-switching-custom-device]
build_number = 14

[repositories.commonbuild-configuration]

[repositories.Switch-Custom-Device]
build_number = 26
