[repositories.BCI-SLSC-LOAD]
build_number = 2

[repositories.BCI-SLSC-VDT]
build_number = 2

[repositories.group-switching-custom-device]
build_number = 1

[repositories.commonbuild-configuration]

[repositories.Switch-Custom-Device]
build_number = 6
